x= int(input("Enter the First Number x :"))
y= int(input("Enter the Second Number y :"))
print(f"The value of x and y is: {x} and {y} respectively")
print(f"The sum of {x} and {y} is: {x+y}")
print(f"The difference of {x} and {y} is: {x-y}")
print(f"The product of {x} and {y} is: {x*y}")
print(f"The division of {x} and {y} is: {x/y}")
print(f"The value of {x} and {y} is: {x//y}")
print(f"The modulus of {x} and {y} is: {x%y}")
print(f"The value of x²  is: {x**2}")
